### ISSUE TITLE
想请教服务端怎么主动向所有客户端广播消息

### ISSUE THREAD

**Issue by shinoyasan** [CzaOrz/Pywss#9]
大哥辛苦了，我在做一个网络摄像头，基于这个websocket的模块。我想要服务端运行在树莓派上，像视频流一样，读取图像数据后推送给所有连接了的客户端。我在 #6 中找到了`ws_send_to_all`，但是它必须要先在客户端请求的情况下才能执行，要先获得request对象，我的理解对吗？我又在#2 中找到了可以定时发送的方法，但我并不想这样做。我想要服务器可以直接调用，这样采集完图像后我直接就可以推送给所有客户端，那么请问下有没有什么可以实现服务端主动推送的办法？

**Comment by shinoyasan** [comment]
没认真看下面的issue。。。

**Comment by CzaOrz** [comment]
考虑到你的需求，我推荐你多加一个路由，专门用来广播给全部用户。
当你读取图片数据后，调用该接口即可广播给其他用户。

**Comment by shinoyasan** [comment]
大哥维护代码真的辛苦了，谢谢大哥指点，您的思路是不是这样的？
```
app.use(middleware)
# 注册路由
app.get("/hello", hello)
# 启动服务
app.run()

def hello(ctx):
  ctx.write("hello world")
```
然后我采集到数据，直接调用hello就可以给所有用户返回吗？

**Comment by CzaOrz** [comment]
我最近在重构，你使用的是最新的还未发布的版本，这个版本可能对websocket支持较少。

你可以查看分支0.0.15版本，里面的用例可以帮到你。

**Comment by shinoyasan** [comment]
太谢谢了
